version: '2'
services:
  client:
    container_name: client
    build: ./client
    ports:
      - '80:80'
    depends_on:
      - server
  server:
    container_name: server
    build: ./server
    ports:
      - '8080:8080'