export const GET_SCRABBLE_WORDS_REQUEST = "GET_SCRABBLE_WORDS_REQUEST";
export const GET_SCRABBLE_WORDS_SUCCESS = "GET_SCRABBLE_WORDS_SUCCESS";
export const GET_SCRABBLE_WORDS_FAILURE = "GET_SCRABBLE_WORDS_FAILURE";
